--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 05/05/2023 16:28:50
-- Server version: 5.7.37
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS practica6msql;

CREATE DATABASE practica6msql
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE practica6msql;

--
-- Create table `coche`
--
CREATE TABLE coche (
  matricula varchar(10) NOT NULL,
  marca varchar(15) DEFAULT NULL,
  modelo varchar(10) DEFAULT NULL,
  color varchar(10) DEFAULT NULL,
  precio float DEFAULT NULL,
  PRIMARY KEY (matricula)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `revision`
--
CREATE TABLE revision (
  codigo int(11) NOT NULL,
  filtro varchar(20) DEFAULT NULL,
  aceite varchar(20) DEFAULT NULL,
  frenos varchar(20) DEFAULT NULL,
  matriculaCoche varchar(10) NOT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE revision
ADD CONSTRAINT fkMatC FOREIGN KEY (matriculaCoche)
REFERENCES coche (matricula),
MODIFY filtro boolean,
MODIFY aceite boolean,
MODIFY frenos boolean;

--
-- Create table `cliente`
--
CREATE TABLE cliente (
  nif varchar(10) NOT NULL,
  nombre varchar(10) DEFAULT NULL,
  direccion varchar(30) DEFAULT NULL,
  ciudad varchar(15) DEFAULT NULL,
  telefono int(11) DEFAULT NULL,
  PRIMARY KEY (nif)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `compra`
--
CREATE TABLE compra (
  nifCliente varchar(10) NOT NULL,
  matriculaCoche varchar(10) NOT NULL,
  PRIMARY KEY (nifCliente, matriculaCoche)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `ukCoche` on table `compra`
--
ALTER TABLE compra
ADD UNIQUE INDEX ukCoche (matriculaCoche);

--
-- Create foreign key
--
ALTER TABLE compra
ADD CONSTRAINT fkCliente FOREIGN KEY (nifCliente)
REFERENCES cliente (nif);

--
-- Create foreign key
--
ALTER TABLE compra
ADD CONSTRAINT fkCoche FOREIGN KEY (matriculaCoche)
REFERENCES coche (matricula);
--
-- eliminar coche
--
ALTER TABLE coche
DROP precio;
-- cambiar telefono por tlf
ALTER TABLE cliente 
CHANGE telefono tlf varchar(20);
-- 
-- Dumping data for table coche
--
INSERT INTO coche VALUES
('c256ag', 'audi', 'a4', 'negro');

-- 
-- Dumping data for table cliente
--
INSERT INTO cliente VALUES
('12345678P', 'jose', 'c/ Alfonso', 'malaga', 942030506);

-- 
-- Dumping data for table revision
--
INSERT INTO revision (codigo, filtro, aceite, frenos, matriculaCoche) VALUES
 (3, 'falso', 'falso', 'falso', 'falso');

-- 
-- Dumping data for table compra
--
INSERT INTO compra VALUES
('12345678P', 'c256ag');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;