--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 05/05/2023 15:06:27
-- Server version: 8.0.28
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS practica42msql;

CREATE DATABASE practica42msql
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE practica42msql;

--
-- Create table `departamento`
--
CREATE TABLE departamento (
  nombred varchar(10) NOT NULL,
  nssd int NOT NULL,
  sexo varchar(2) DEFAULT NULL,
  numeroempleados int DEFAULT NULL,
  nssempleado int NOT NULL,
  fechainicio date DEFAULT NULL,
  PRIMARY KEY (nombred, nssd)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `ukdep` on table `departamento`
--
ALTER TABLE departamento
ADD UNIQUE INDEX ukdep (nssempleado);

--
-- Create table `proyecto`
--
CREATE TABLE proyecto (
  nombrep varchar(10) NOT NULL,
  numerop int NOT NULL,
  localizacion varchar(30) DEFAULT NULL,
  nombrecontrola varchar(10) NOT NULL,
  nsscontrola int DEFAULT NULL,
  PRIMARY KEY (nombrep, numerop)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE proyecto
ADD CONSTRAINT fkpro FOREIGN KEY (nombrecontrola, nsscontrola)
REFERENCES departamento (nombred, nssd);

--
-- Create table `localizaciondep`
--
CREATE TABLE localizaciondep (
  nombred varchar(10) NOT NULL,
  numerod int NOT NULL,
  localizacion varchar(30) DEFAULT NULL,
  PRIMARY KEY (nombred, numerod)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE localizaciondep
ADD CONSTRAINT fklocal FOREIGN KEY (nombred, numerod)
REFERENCES departamento (nombred, nssd);

--
-- Create table `empleado`
--
CREATE TABLE empleado (
  nss int NOT NULL,
  nombre varchar(10) DEFAULT NULL,
  apellido varchar(15) DEFAULT NULL,
  iniciales varchar(3) DEFAULT NULL,
  sexo varchar(2) DEFAULT NULL,
  direccion varchar(20) DEFAULT NULL,
  salario float DEFAULT NULL,
  fechanacimiento date DEFAULT NULL,
  nombred varchar(10) DEFAULT NULL,
  numerod int DEFAULT NULL,
  PRIMARY KEY (nss)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE empleado
ADD CONSTRAINT fkdepemp FOREIGN KEY (nombred, numerod)
REFERENCES departamento (nombred, nssd);

--
-- Create foreign key
--
ALTER TABLE departamento
ADD CONSTRAINT fkempd FOREIGN KEY (nssempleado)
REFERENCES empleado (nss);

--
-- Create table `trabajaen`
--
CREATE TABLE trabajaen (
  nssempleado int NOT NULL,
  nombrep varchar(10) NOT NULL,
  numerop int NOT NULL,
  horas int DEFAULT NULL,
  PRIMARY KEY (nssempleado, nombrep, numerop)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE trabajaen
ADD CONSTRAINT fktraem FOREIGN KEY (nssempleado)
REFERENCES empleado (nss);

--
-- Create foreign key
--
ALTER TABLE trabajaen
ADD CONSTRAINT fktrap FOREIGN KEY (nombrep, numerop)
REFERENCES proyecto (nombrep, numerop);

--
-- Create table `supervisa`
--
CREATE TABLE supervisa (
  supervisor int NOT NULL,
  supervisado int NOT NULL,
  PRIMARY KEY (supervisor, supervisado)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `ukemp2` on table `supervisa`
--
ALTER TABLE supervisa
ADD UNIQUE INDEX ukemp2 (supervisado);

--
-- Create foreign key
--
ALTER TABLE supervisa
ADD CONSTRAINT fksuper FOREIGN KEY (supervisor)
REFERENCES empleado (nss);

--
-- Create foreign key
--
ALTER TABLE supervisa
ADD CONSTRAINT fksuper2 FOREIGN KEY (supervisado)
REFERENCES empleado (nss);

--
-- Create table `dependiente`
--
CREATE TABLE dependiente (
  nombredependiente varchar(10) NOT NULL,
  nssempleado int NOT NULL,
  sexo varchar(2) DEFAULT NULL,
  fechanac date DEFAULT NULL,
  parentesco varchar(20) DEFAULT NULL,
  PRIMARY KEY (nombredependiente, nssempleado)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE dependiente
ADD CONSTRAINT fkdep FOREIGN KEY (nssempleado)
REFERENCES empleado (nss);

-- 
-- Dumping data for table departamento
--
INSERT INTO departamento VALUES
('reparto', 2, 'H', 20, 7, '2015-04-10'),
('ventas', 1, 'H', 10, 3, '2010-05-05');

-- 
-- Dumping data for table proyecto
--
INSERT INTO proyecto VALUES
('algo', 2, 'santander', 'reparto', 2),
('peña', 1, 'valladolid', 'ventas', 1);

-- 
-- Dumping data for table empleado
--
INSERT INTO empleado VALUES
(3, 'jose', 'castillo', 'jct', 'H', 'avda camilo alonso', 1000, '1996-02-02', 'ventas', 1),
(7, 'juan', 'ortega', 'jod', 'NB', 'c/ alta', 2000, '1999-01-30', 'reparto', 2);

-- 
-- Dumping data for table trabajaen
--
INSERT INTO trabajaen VALUES
(3, 'peña', 1, 20);

-- 
-- Dumping data for table supervisa
--
INSERT INTO supervisa VALUES
(7, 3);

-- 
-- Dumping data for table localizaciondep
--
INSERT INTO localizaciondep VALUES
('reparto', 2, 'santander'),
('ventas', 1, 'malaga');

-- 
-- Dumping data for table dependiente
--
INSERT INTO dependiente VALUES
('jose', 3, 'H', '1996-02-21', 'hermano');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;