--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 02/05/2023 18:02:45
-- Server version: 5.7.37
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS practica3msql;

CREATE DATABASE practica3msql
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE practica3msql;

--
-- Create table `poblacion`
--
CREATE TABLE poblacion (
  codpob int(11) NOT NULL,
  nombre varchar(15) DEFAULT NULL,
  PRIMARY KEY (codpob)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `coches`
--
CREATE TABLE coches (
  matricula int(11) NOT NULL,
  PRIMARY KEY (matricula)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `clientes`
--
CREATE TABLE clientes (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(15) DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `relacion`
--
CREATE TABLE relacion (
  codcliente int(11) NOT NULL,
  codpob int(11) NOT NULL,
  matricula int(11) NOT NULL,
  PRIMARY KEY (codcliente, codpob, matricula)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE relacion
ADD CONSTRAINT fkcliente FOREIGN KEY (codcliente)
REFERENCES clientes (codigo);

--
-- Create foreign key
--
ALTER TABLE relacion
ADD CONSTRAINT fkcoches FOREIGN KEY (matricula)
REFERENCES coches (matricula);

--
-- Create foreign key
--
ALTER TABLE relacion
ADD CONSTRAINT fkpob FOREIGN KEY (codpob)
REFERENCES poblacion (codpob);

-- 
-- Dumping data for table poblacion
--
INSERT INTO poblacion VALUES
(21, 'tarragona'),
(74, 'valencia'),
(98, 'asturias');

-- 
-- Dumping data for table coches
--
INSERT INTO coches VALUES
(1234),
(5697),
(9874);

-- 
-- Dumping data for table clientes
--
INSERT INTO clientes VALUES
(1, 'Javi'),
(2, 'jose'),
(3, 'juan');

-- 
-- Dumping data for table relacion
--
INSERT INTO relacion VALUES
(2, 21, 1234),
(3, 74, 5697),
(1, 98, 9874);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;