--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 05/05/2023 15:56:10
-- Server version: 5.7.37
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS practica5msql;

CREATE DATABASE practica5msql
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE practica5msql;

--
-- Create table `profesor`
--
CREATE TABLE profesor (
  dni varchar(9) NOT NULL,
  nombre varchar(15) DEFAULT NULL,
  direccion varchar(40) DEFAULT NULL,
  telefono int(11) DEFAULT NULL,
  PRIMARY KEY (dni)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `modulo`
--
CREATE TABLE modulo (
  codigo int(11) NOT NULL,
  nombre varchar(15) DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `imparte`
--
CREATE TABLE imparte (
  dniProfe varchar(9) NOT NULL,
  codigoMod int(11) NOT NULL,
  PRIMARY KEY (dniProfe, codigoMod)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `ukImp` on table `imparte`
--
ALTER TABLE imparte
ADD UNIQUE INDEX ukImp (codigoMod);

--
-- Create foreign key
--
ALTER TABLE imparte
ADD CONSTRAINT fkMod FOREIGN KEY (codigoMod)
REFERENCES modulo (codigo);

--
-- Create foreign key
--
ALTER TABLE imparte
ADD CONSTRAINT fkProfe FOREIGN KEY (dniProfe)
REFERENCES profesor (dni);

--
-- Create table `alumno`
--
CREATE TABLE alumno (
  expediente int(11) NOT NULL,
  nombre varchar(15) DEFAULT NULL,
  apellidos varchar(25) DEFAULT NULL,
  fecha_nac date DEFAULT NULL,
  PRIMARY KEY (expediente)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `delegado`
--
CREATE TABLE delegado (
  expedienteDel int(11) NOT NULL,
  expedienteAl int(11) NOT NULL,
  PRIMARY KEY (expedienteDel, expedienteAl)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `ukAlD` on table `delegado`
--
ALTER TABLE delegado
ADD UNIQUE INDEX ukAlD (expedienteAl);

--
-- Create foreign key
--
ALTER TABLE delegado
ADD CONSTRAINT fkAl1 FOREIGN KEY (expedienteDel)
REFERENCES alumno (expediente);

--
-- Create foreign key
--
ALTER TABLE delegado
ADD CONSTRAINT fkAl2 FOREIGN KEY (expedienteAl)
REFERENCES alumno (expediente);

--
-- Create table `cursa`
--
CREATE TABLE cursa (
  expedienteAl int(11) NOT NULL,
  expedienteMod int(11) NOT NULL,
  PRIMARY KEY (expedienteAl, expedienteMod)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE cursa
ADD CONSTRAINT fkAlC1 FOREIGN KEY (expedienteAl)
REFERENCES alumno (expediente);

--
-- Create foreign key
--
ALTER TABLE cursa
ADD CONSTRAINT fkAlC2 FOREIGN KEY (expedienteMod)
REFERENCES modulo (codigo);

-- 
-- Dumping data for table profesor
--
INSERT INTO profesor VALUES
('72258621P', 'Jorge', 'C/ Antonio Mendoza', 0);

-- 
-- Dumping data for table modulo
--
INSERT INTO modulo VALUES
(3, 'informatica');

-- 
-- Dumping data for table alumno
--
INSERT INTO alumno VALUES
(212, 'Ricardo', 'Montoya', '2002-06-06');

-- 
-- Dumping data for table imparte
--
INSERT INTO imparte VALUES
('72258621P', 3);

-- 
-- Dumping data for table delegado
--
INSERT INTO delegado VALUES
(212, 212);

-- 
-- Dumping data for table cursa
--
INSERT INTO cursa VALUES
(212, 3);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;